language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.5.1 WP_MULTISITE=0
    - WP_VERSION=3.5.1 WP_MULTISITE=1

before_script:
    - export WP_TESTS_DIR=/tmp/wordpress-tests/
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
